langage: python

python:
- '3.8'

addons:
  firefox: latest

before_script:
- wget https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
- mkdir geckodriver
- tar -xzf geckodriver-v0.27.0-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver
- sudo apt-get install xvfb
- Xvfb :10 -ac &
- pip install -r requirements.txt

branches:
  only:
  - develop
env:
  global:
  - secure: zMsdDb3c5ehuNcH54VWz+OmTeEZ7JtXSi7P5+yOlI7b/L+mWfeKA7zYSLxh/xRpmhE2grBPVLmmspDZixTJvFy0HHPrOzPyrp2Hdp+9j5z3Fo+PpjB2NsAkMv6hEgQYuZVl/X5HkrzKqomj2nl0vO1OFMn040GjTTB/t04uK2ZJo2PS1WJl85iKgTxB3IPmPM/mzCjgW0iUbEn04k27PW6OtIHe+ZEdM43Hax57AH6H1Z5oFhIaXLYT2d7D9Zx1i4GANwHUwRUTjYNk1CoiRv6ixo/UgaHBJjEWn1RjKHjzvG+D5d5rlHxY6td+ccjaqx9tv808tmPjzQ0YK9CLsr5gdgHzEqF0elSYoYAdWiAILL2fGBblAXFblUpZvwIFWq+F2YKQvJ8pJObFrfeTHYJUthhG8tveE63gcBfNYvLEB8shyZE+YhLKJLVmDAiaxtSvLdP7bqYZAJQ4rZKX/IlB9HLrJJGl0eAkBKyayxiuS3ZQWj4Ilp39ePPStY3rTf92VISFeuEXUaHk1sXB5Z/2Wnq2G3nWPwVSP/zqRFPzjuWPF96NuRgKBAKOQcQ4xDdc78tzJCSTyxlFu89pV7IEL1xSMqVt+t71FtPKvysS+WH9ANtviWox9bVWS/Z5h9VsRY79ya6xrAFScwYkt+8cormcXZ275b/4uPgIkXX4=
  - secure: QRr4jPi7B5Zl1ZYcq2/P4m8/miCF97yAh5zYtT/Sz8LJT2mB9e82tYgP8iMBht6CQNnEGu8NVwa3zoNtv9DQTINO7/iU28ELYydyOQ7URapi+EwYdc2LvlAd0Oug2VQ05BJvbU87T4NFbsOJ0hsT6bpxoYUBRF/zcWiU0BFzFJ9x/J68NoQtoN5E3VFX3Cue90o6yKN3yHeP6A6d0CyiS8QjvQ/dRo/lMXLZF5cSfTZsAur2Napk7vTgcwK5I1XhsFBqJNRtm3q8McoxPnYuDd+peM+l2nAgATQaslB0CfsfBR5s2B9HmngDlgY4tsX9ilDJ1erXr5FVemz4SumFqR1yNYMhzUoA/fIzgGOLYTOd5Wf67BduzUrZtw12Os5UinASSguWgjQHjV5tGLmoNi2CXGkbYXUdCaRulXRvHb2UxbUE0fa1eLWmgMbq+0DTOqj6GpMf3ARzOxq5gKvi6HbxwcehwAPCmG45hBXmLXzCCmvvgAytXG3WuIIRH0i1cl5ZiCEy7ErN6zvccRjqksdNWmuFtS4ClFKkxghBQfoAR8XF+P3EaHvRm7lfxmx9ha1L9eukLDT5KSIM5DnLLKqIWktashrfB1YS7ws1wXwU6KXQEtDztJffOTHVe1F6vxsYnAuT/VndlmcDl9r94k+ausDUOCAxcn7DHO+VwI8=
  - secure: vR8oQWiU1jrUTAb2UbHcc/+LPJWofL312+8tJoPM5bvGRorJJoZorkfksZXdHo/E5xpQH8mqsBXfzREsdNg2pUYGdOPcq47D1C0sWxDPMNgAOzvVJXc93odZno8kk6PZ/pE05FFywhMo+PB76+NjeT/CYrOtry6BzN9yMSpR1xaEjcY3Y6+qlP7h+qd1P2rXIh8Fjvq1n8h2WWhSHW1VBDihljabll9qKLqstz2sxKvIqJoN6sC4oRfoKbYr2EGoSOi9IsDgL2WEbEYEdtmKUfi1+mS3lgdzPZ045Uh8f4IcsRwO0A2unIpojWQanfcjTcEpKMDM46afLXW2IdDh9F9uEUqaAyjFn393mffxacPvY5/Vd+3mb0m3mYb/Bpl9NHmfU+AMvBO2MrlOEuRMuhzYxK8ca9+ot6KnHB6xhbh2N1BdjH5XVjcNhNTWlkq67YnEdeE5eSCAxqvU12/3n9msl8Np/VDb+RgIZetl6PsdwkoF+1wJOloBv/bsMQ3b5OdiycgguAnNTkG74G91A+sW86xgaS44aQDYiA5bpYV5LVO2AFx6ImbTOccES50HuUUQaKe4g7zHmEjhMigNrmLkufeXMozGji1Hi4jQNJuscdQBo2bzKcJ70OGpyyveP8DpN17iJWMGZO5l0OWaFV3FrmL4PdVyk8yNRuLbeAo=
  - DJANGO_SETTINGS_MODULE="settings.travis"
  - DISPLAY=:10

services:
- postgresql
script:
- "./manage.py test tests"
